{% set version = "0.14.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-moments
  version: {{ version|replace("-", "_") }}

source:
  fn: moments_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/moments_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/moments/moments_{{ version }}.tar.gz
  sha256: 2ed2b84802da132ae0cf826a65de5bfa85042b82e086be844002fe1ce270d864

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('moments')"  # [not win]
    - "\"%R%\" -e \"library('moments')\""  # [win]

about:
  home: http://www.r-project.org, http://www.komsta.net/
  license: GPL (>= 2)
  summary: "Functions to calculate: moments, Pearson's kurtosis, Geary's kurtosis and skewness; tests related to them (Anscombe-Glynn, D'Agostino, Bonett-Seier)."

  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3  # [unix]
  license_file: {{ environ["PREFIX"] }}\R\share\licenses\GPL-3  # [win]

extra:
  recipe-maintainers:
    - conda-forge/r
