travis:
  secure:
    BINSTAR_TOKEN: lHwAhvfb+4MfNqhq4e7TDn+rvSQVrweqQ7mLSeL6bmmKDLHtxWRtFYnWHgSsxbaP2CkiLXkdOLMWUCtEkMdHPkoYxhHzyf2p5fVSm6FD+MIwNHeoMucPBF4cOJT+QCDbfOqeHcrsPnk+nA3ZPepvuvKy5ZquxiJ7RyFZb4IrU5Itkt3jidkh0YWQCSkwhYtjkw205Ok1kDDb0WtbSRDx8sp2/3b3B/Mq6/woFzwJALL/8Q4ri+1boEe8kPHDBydfaTO1LNmfG/APapVw3dSCBLqGGrPyfD7SCYIDoE8FdeDYLJtahqitD5YgaUBIt1HXw95gNwKOFYGZfPh8NON7qm2gY633c5Ac+eRreOfFpckT8DeOXNicYgIagl7DG1dqiik/m1QLAKZjxWR3IU2loBB/BJXSY0Zp4MU8rS5xxQJPdyq/7KqRXoPUnYvqvSKIjIkT4HGOVnjtpftkGkc+qG8jl+UOA6YcbOM2Fct/x7bCuFtMSnhIegC51qU17nHU93DZ6arO4G0iJ9xrQ7J4UOVVgxH2PFVwmMZ64DBtPuagxnWKp6FXEQueOaBMS7ZjgL+5yZp1bjdsqn06GINqvs17fgADPbrp4SKo7ycKmV/x91f0SOAQQN5QMvLTKq8eJ+hcQMJ48i9N750/nGUKuS0jCdTV8V086j5DSdA6i2Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
