travis:
  secure:
    BINSTAR_TOKEN: epEs6rwTWwYCabQnIQycTkJtJXWzvCxvw7SEVKsxw0I3TV5h26KuaINjq7tkfIGV/VpGvdwyoOg83gdRsEI5J12u8x459kOBVlQO8zGOxpCMeLVboo0cZPtoM8bN/6D/WwMb9K5QcQhIRdR4P0qi7/8xt0YeQS9sPKjtvkvKgOdSjX0wZxz25p8iVnZ4LAeL6NJyNGIK/CGt/edelc5OfHp3olxSuAabCRvi+PjoWqRaNn9w6bx+K3oz+MaFSPt3dSoJqdPG0NLNxTzIDLx40TT0q9+qaV10qxk2dRySzk4ExfNTTC1D9D/5Dc+Km3lpWZVDylZNoOJ0lB7qKky5c3FxntuK5lvDNUQATUIeEdk8W0/mu1AwZWzyaEG1E2wT9oiAwEU4inCJbj84UfSfiN7Z7plpXKz8XBfqGyf4Rut6uugv81UD36zLaa3JZvnVuf54O0SoAtLStZi6G5Yyr/I8m4qzHuJoX8ZEeVI1j5Cv8xvD3tJPIIr4gVgjdttTTuV/Ig+CTVdZhhA1vMCrydiEQmQxblKK2FQRzQLZCd+V8h0hHGuInjhPQ9EYzCxXgv/W7tqEfTP7FyWWeQBn8bDMrE0+hwwEFaTFKysLPXg4hsLbHHOulS19JSFOcWUcXST210JltASGbA/lK2x2ZRGmRtqrTFzJoMw/kDooQxs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
